### ISSUE TITLE
[Feat Request] Be able to add remote docker server thru docker API (port 2375/2376)

### ISSUE THREAD

**Issue by edersong** [LooLzzz/docking-station#1]
It will be awesome if we can add external docker server thru docker API (ports 2375 or 2376) like [Portainer](https://docs.portainer.io/admin/environments/add/docker/api) or [Dozzle](https://dozzle.dev/guide/remote-hosts)

**Comment by bryceprutsos** [comment]
I agree or be able to connect to multiple remote docker hosts.

**Comment by princejosuah** [comment]
+1 to this idea

**Comment by LooLzzz** [comment]
I've made a small modification to the `python_on_whales` docker client I'm using in the backend.

Unfortunately I don't have a proper remote docker host to test this on,  
But according to `python_on_whales` [docs](https://gabrieldemarmiesse.github.io/python-on-whales/docker_client/), it should work as expected.

Use the new `loolzzz/docking-station:dev` [tag](https://hub.docker.com/layers/loolzzz/docking-station/dev/images/sha256-ea8ba6cefa448dce5d3f9f614a9424c1334a93609450af47530ab31c3ecc1fee?context=explore)  
and add the following to `/app/config/settings.yml` file:

```yml
server:
  ...

  python_on_whales__docker_client_config:
    # https://gabrieldemarmiesse.github.io/python-on-whales/docker_client/
    host: unix:///var/run/docker.sock  # or whatever else docker host you want here
```

Let me know if this works so I can move this to the main branch.
