### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by robflate** [LooLzzz/docking-station#2]
In the attached image, all 4 of the containers Docking Station shows as having an update available are already on the updated version.

<img width="1459" alt="Screenshot 2024-07-12 at 21 31 31" src="https://github.com/user-attachments/assets/fc3068ca-885c-482d-8bd1-f8ce0df04340">

[docking-station-2024-07-12T20-35-52.log](https://github.com/user-attachments/files/16199118/docking-station-2024-07-12T20-35-52.log)

**Comment by LooLzzz** [comment]
Thank you for your feedback.

I'll take a look

**Comment by robflate** [comment]
```
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 10m
    volumes:
      - $CONFIG/autobrr/config:/config
    environment:
      TZ: $TZ
    user: $PUID:$PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.autobrr-rtr.entrypoints=https"
      - "traefik.http.routers.autobrr-rtr.rule=Host(`autobrr.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.autobrr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.autobrr-rtr.service=autobrr-svc"
      - "traefik.http.services.autobrr-svc.loadbalancer.server.port=7474"
```
```
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:nightly
    restart: unless-stopped
    networks:
      t3_proxy:
        ipv4_address: $IP_READARR
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIG/readarr:/config
      - $DATA:/data
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.readarr-rtr.entrypoints=https"
      - "traefik.http.routers.readarr-rtr.rule=Host(`readarr.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.readarr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.readarr-rtr.service=readarr-svc"
      - "traefik.http.services.readarr-svc.loadbalancer.server.port=8787"
```
```
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    restart: unless-stopped
    networks:
      - t3_proxy
    volumes:
      - $CONFIG/recyclarr:/config
    environment:
      TZ: $TZ
      RECYCLARR_CREATE_CONFIG: true
      CRON_SCHEDULE: "@daily"
    user: $PUID:$PGID
```
```
  beets-audiobooks:
    container_name: beets-audiobooks
    image: lscr.io/linuxserver/beets:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG/beets-audiobooks/config:/config
      - $CONFIG/beets-audiobooks/scripts:/custom-cont-init.d:ro # https://github.com/seanap/beets-audible/discussions/8#discussioncomment-8176329
      - $VOLUMES/htpc08/media/audiobooks:/audiobooks
      - $DATA/import/audiobooks:/input # manually downloaded books go here
      - $CONFIG/libation/opt/libation/books:/libation # books dowloaded by Libation
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.beets-audiobooks-rtr.entrypoints=https"
      - "traefik.http.routers.beets-audiobooks-rtr.rule=Host(`beets-audiobooks.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.beets-audiobooks-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.beets-audiobooks-rtr.service=beets-audiobooks-svc"
      - "traefik.http.services.beets-audiobooks-svc.loadbalancer.server.port=8337"
```
