### ISSUE TITLE
Unable to run update 

### ISSUE THREAD

**Issue by pavolholes** [LooLzzz/docking-station#30]
Hi @LooLzzz,
I wanted to give a try to this project since it looks really nice but the update doesn't work, can you please let me know what I'm doing wrong?
My containers are all built using Portainer Stacks so I've provided this folder in the config and the docking-station was able to parse it to detect all containers and stacks but when I run update it ends with error - I tried three different containers.

Error:
```
stat /data/compose/111/docker-compose.yml: no such file or directory
```

Screenshot:
![image](https://github.com/user-attachments/assets/b8a60f06-8674-4aa7-b499-d1f3e8f7c407)

compose:
```
services:
  docking-station:
    image: loolzzz/docking-station
    container_name: docking-station
    restart: unless-stopped
    ports:
      - 3003:3000
    volumes:
      - /home/pavol/DockerVolumes/docking-station/config:/config
      - /home/pavol/DockerVolumes/docking-station/data:/data
      - /home/pavol/DockerVolumes/docking-station/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      # you should add mount points for each containers' docker-compose file you intend on update using this tool
      # i usually put everything in a single neat folder under
      #  ⚠️ left stacks path == right stacks path (MUST)
      - /home/pavol/DockerVolumes/portainer/compose:/home/pavol/DockerVolumes/portainer/compose
    environment:
      - WEB_PORT=3000
      # - SERVER_PORT=3001
```

Manual run of the `stat` command with correct path:
```
$ stat /home/pavol/DockerVolumes/portainer/compose/111/docker-compose.yml
  File: /home/pavol/DockerVolumes/portainer/compose/111/docker-compose.yml
  Size: 850             Blocks: 8          IO Block: 4096   regular file
Device: 8,18    Inode: 8919737     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/   pavol)   Gid: ( 1000/   pavol)
Access: 2024-06-25 23:12:31.603785694 +0200
Modify: 2024-06-25 23:12:30.383765394 +0200
Change: 2024-06-25 23:12:30.383765394 +0200
 Birth: 2023-03-18 22:56:15.828257230 +0100
```

Side notes:
- At first I was not able to get the WEB UI working because I changed the `WEB_PORT` env. variable to `WEB_PORT=3003` but it wasn't taken in the consideration and in the logs I still saw `[WEB]    - Local:        http://b371e4ec3665:3000` so I left it on 3000 and I used `ports: 3003:3000` which worked and I was able to see the GUI. Why are the `WEB_PORT` and `SERVER_PORT` in the example and can you add some comments how to use them if they are actually needed (which seems like not)?
- Above error is not captured in any of the logs in the logs folder, it's visible only in the details of the GUI.
- The update wasn't marked as Failed but as Finished. It would be nice to let user know it didn't succeed and ideally expand the logs of the section where the error occured - for me expand the `docker compose up --pull always` section since the error occured there.

Thank you very much!
