### ISSUE TITLE
[SERVER] KeyError: 'docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0'

### ISSUE THREAD

**Issue by cryptedx** [LooLzzz/docking-station#35]
Hi,

I am von version 0.3.1. I tried a clean re-install. 

**compose-yaml**

```yaml
services:
  docking-station:
    image: loolzzz/docking-station
    restart: unless-stopped
    ports:
      - 3002:3000
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /opt/stacks:/opt/stacks
```

[docking-station-server.log](https://github.com/user-attachments/files/17166034/docking-station-server.log)

Thanks

**Comment by JanisV** [comment]
Same for me with `KeyError: 'docker.io/redis:6.2-alpine'` on v0.4.2

**Comment by LooLzzz** [comment]
Can you please post the contents of `/config/settings.yml`?

Also, try the following again:

* stop DS: `docker compose down`
* delete `./config` and `./data` contents
* start DS again: `docker compose up -d`

I've added custom service to my stacks which is using `docker.io/redis:6.2-alpine` as an image,  
Unfortunately I'm not getting the `KeyError` when entering Docking Station.

**Comment by di5cord20** [comment]
I'm experiencing the same issue as @cryptedx .  Tried the following but no change 
```
python_on_whales__ignored_image_prefixes:
  - docker.io/tensorchord/
  - docker.io/library/
  - docker.io/ 
```

**Comment by LooLzzz** [comment]
I'm sorry guys,  
but I'm not able to reproduce this issue on my side.

Here's the  compose file I'm trying to reproduce with:

```yml
services:
  redis-test:
    image: docker.io/redis
    command: ["sleep", "infinity"]

  pgvecto-rs:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    command: ["sleep", "infinity"]
```

Everything is loading just fine, no errors

![image](https://github.com/user-attachments/assets/0d1bdac6-36d8-42a2-bb88-d5682121edbf)

---

If you have the know-how, try to debug it yourself and let me know if you find anything.

I have a fully working devcontainer at the root of the repository.  
Just adjust the stacks location in `volumes:` to the proper path for your machine.

---

Closing this as can't reproduce.

**Comment by Arcturuss** [comment]
can confirm, removing sha256 from immich docker-compose file fixes it.
@LooLzzz could you please reopen this issue? or maybe it will be tracked in some other place with other similar KeyError problems?

**Comment by LooLzzz** [comment]
Again, the thing is -
I can't reproduce it on my system

```yml
services:
  redis-test:
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    command: ["sleep", "infinity"]

  pgvecto-rs:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command: ["sleep", "infinity"]
```

Seems fine with no errors in the console  
What am I missing here?

![image](https://github.com/user-attachments/assets/8bde315f-7b9d-4d93-8c77-ef29490e6c6e)
