### ISSUE TITLE
Error when loading Web UI

### ISSUE THREAD

**Issue by Dart2112** [LooLzzz/docking-station#53]
https://pastebin.com/eT8iA7JJ

When I first launch the container I get this error. After which it successfully checks the version of all my containers. But the Web UI still shows "* But nobody came."

My compose file is as below
```
services:
  docking-station:
    image: loolzzz/docking-station
    container_name: docking-station
    labels:
      *Traefik and HomePage labels removed*
    volumes:
      - /home/name/Docker/docking-station/config:/config
      - /home/name/Docker/docking-station/data:/data
      - /home/name/Docker/docking-station/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /home/name/Docker/portainer/compose/:/home/name/Docker/portainer/compose/
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
```
