### ISSUE TITLE
"But nobody came" no matter what

### ISSUE THREAD

**Issue by xanty9** [LooLzzz/docking-station#55]
```
services:
  docking-station:
    image: loolzzz/docking-station
    restart: unless-stopped
    ports:
      - 3011:3000
    volumes:
      - /home/xanty/data/config/dockingstation/config:/config
      - /home/xanty/data/config/dockingstation/data:/data
      - /home/xanty/data/config/dockingstation/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      # you should add mount points for each containers' docker-compose file you intend on update using this tool
      # i usually put everything in a single neat folder under
      #  ⚠️ left stacks path == right stacks path (MUST)
      - /home/xanty/data/dockercompose:/home/xanty/data/dockercompose
```

[logFile.txt](https://github.com/user-attachments/files/17407057/logFile.txt)
