### ISSUE TITLE
Can't manually update

### ISSUE THREAD

**Issue by PonyOny** [LooLzzz/docking-station#69]
I can't manually update my container, when trying to update it shows he following error, I have all container in a docker-compose file and this file is mapped as described in the documentation (- /mnt/compose-files:/mnt/compose-files), any idea why it's looking for the docker-compose file in the location you can see in the screenshot?

![Image](https://github.com/user-attachments/assets/534306ae-17af-409f-be98-9e49d9747538)

**Comment by Famku** [comment]
you have to mount the file like this:

- /home/famku/beszel-agent/docker-compose.yml:/home/famku/beszel-agent/docker-compose.yml

**Comment by PonyOny** [comment]
I have tried that and facing the same issue, I have also ssh into the container and can see that the docker-compose.yml file is located in the same directory as mine.

**Comment by PonyOny** [comment]
Is it mandatory to have a docker-compose.yml for each container? I have only one docker-compose.yml file that includes all containers, and does the folder structure naming have to be the same as the docker image with the compose file in it?
I have mounted my compose file like this.

- /home/ponyony/docker/docker-compose.yml:/home/ponyony/docker/docker-compose.yml

**Comment by Famku** [comment]
I dont think the folder structure naming have to be the same as the docker image with the compose file. But I think it is not a good Idea to use one docker-compose.yml generally.

Just try it with one service and one docker-compose.yml to test it.

**Comment by theoqrz** [comment]
I also have this same problem.

I have all my compose files on path `/docker/stacks/zzz` with each zzz folder being the name of the container.
In the compose file of docking-station I've mounted a volume as `/docker/stacks:/docker/stacks`
When I refresh the docking station web ui I can see all my containers and a bunch of pending updates but when I click on _**Update Service**_ it shows me the **_no such file or directory_** error.

![Image](https://github.com/user-attachments/assets/e43c8b77-751b-4a92-aa80-ed74e5228ad0)

![Image](https://github.com/user-attachments/assets/57757886-8f4d-4052-8932-f1e24535b2f5)

I have no idea why it is trying to find the compose file in that path. Yes, I have installed metube in the /metube folder but shouldn't docking-station follow the path that is set in its compose file?

**Comment by Osvaldo-Net** [comment]
I have the same problem :( <img width="1235" height="648" alt="Image" src="https://github.com/user-attachments/assets/56220165-1581-4721-be17-854d41bb6f20" />

**Comment by lesleypersyn** [comment]
Whatever i do, i get "open /app/docking-station-app/docker-compose.yaml: no such file or directory"
The main purpose of this tool isn't working. Is this a general problem?

**Comment by mixpc** [comment]
Same case here. Documented:

docker-compose.yml
```
services:
  docking-station:
    image: loolzzz/docking-station
    container_name: docking-station
    restart: unless-stopped
    ports:
      - 3004:3000
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker/transmission/docker-compose.yml:/home/user/docker/transmission/docker-compose.yml
```

settings.yml (default values)
```
server:
  cache_control_max_age: 1d
  discovery_strategy: opt-out
  dryrun: false
  ignore_compose_stack_name_keywords:
    - devcontainer
  possible_homepage_labels:  # order matters!
    - org.label-schema.url
    - org.opencontainers.image.url
    - org.opencontainers.image.source
  possible_image_version_labels:  # order matters!
    - org.label-schema.version
    - org.opencontainers.image.version
  python_on_whales__ignored_image_prefixes:
    - docker.io/library/
    - docker.io/
  time_until_update_is_mature: 1w

auto_updater:
  enabled: false
  interval: 1d
  max_concurrent: 1
```

docking-station updates other containers with no problems but produces an error with transmission


```
sudo docker inspect -f '{{ index .Config.Labels "build_version" }}' lscr.io/linuxserver/transmission:latest
Linuxserver.io version:- 4.0.6-r4-ls304 Build-date:- 2025-07-29T10:46:43+00:00
```

docking-station reports
```
version
4.0.6-r4-ls304
update available
4.0.6-r4-ls310
```

docker-compose.yml
```
---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
```

https://docs.linuxserver.io/images/docker-transmission/
Release V4.0.6-R4-LS310

docking-station execution details

`open /home/user/docker/transmission/docker-compose.yml: no such file or directory`

```
user@server:~/docker/transmission$ pwd
/home/user/docker/transmission

user@server:~/docker/transmission$ ls -alh docker-compose.yml
-rw-rw-r-- 1 user user 621 Aug 30 14:31 docker-compose.yml
```

sudo docker compose logs -f
```
docking-station  | [SERVER] INFO:     127.0.0.1:40800 - "GET /api/settings HTTP/1.1" 200
docking-station  | [SERVER] INFO:     127.0.0.1:40804 - "GET /api/stacks HTTP/1.1" 200
docking-station  | [SERVER] INFO:     127.0.0.1:40812 - "GET /api/settings HTTP/1.1" 200
docking-station  | [SERVER] INFO:     127.0.0.1:36998 - "POST /api/stacks/batch_update HTTP/1.1" 200
docking-station  | [SERVER] INFO:     127.0.0.1:37010 - "GET /api/stacks/transmission/transmission/task?offset=0 HTTP/1.1" 200
docking-station  | [SERVER] INFO:     127.0.0.1:37020 - "GET /api/stacks/transmission/transmission/task?offset=0 HTTP/1.1" 200
docking-station  | [SERVER] INFO:     127.0.0.1:37028 - "GET /api/stacks/transmission/transmission/task?offset=2 HTTP/1.1" 200
docking-station  | [SERVER] DEBUG:    regctl image digest request: lscr.io/linuxserver/transmission:latest
docking-station  | [SERVER] INFO:     regctl image digest response: lscr.io/linuxserver/transmission@sha256:85657644282bffa1adac16cd42c19a8a0210024bc00793c475814f00b095807c
docking-station  | [SERVER] INFO:     127.0.0.1:37040 - "GET /api/stacks/transmission/transmission?no_cache=true HTTP/1.1" 200
```

docking-station-server.log
```
INFO:     2025-09-18 10:16:10 [uvicorn.error] Application startup complete.
INFO:     2025-09-18 10:16:10 [uvicorn.error] Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
INFO:     2025-09-18 10:16:25 [uvicorn.access] 127.0.0.1:40800 - "GET /api/settings HTTP/1.1" 200
INFO:     2025-09-18 10:16:26 [uvicorn.access] 127.0.0.1:40804 - "GET /api/stacks HTTP/1.1" 200
INFO:     2025-09-18 10:16:26 [uvicorn.access] 127.0.0.1:40812 - "GET /api/settings HTTP/1.1" 200
INFO:     2025-09-18 10:16:37 [uvicorn.access] 127.0.0.1:36998 - "POST /api/stacks/batch_update HTTP/1.1" 200
INFO:     2025-09-18 10:16:37 [uvicorn.access] 127.0.0.1:37010 - "GET /api/stacks/transmission/transmission/task?offset=0 HTTP/1.1" 200
INFO:     2025-09-18 10:16:37 [uvicorn.access] 127.0.0.1:37020 - "GET /api/stacks/transmission/transmission/task?offset=0 HTTP/1.1" 200
INFO:     2025-09-18 10:16:38 [uvicorn.access] 127.0.0.1:37028 - "GET /api/stacks/transmission/transmission/task?offset=2 HTTP/1.1" 200
DEBUG:    2025-09-18 10:16:38 [api.services.regctl] regctl image digest request: lscr.io/linuxserver/transmission:latest
INFO:     2025-09-18 10:16:39 [api.services.regctl] regctl image digest response: lscr.io/linuxserver/transmission@sha256:85657644282bffa1adac16cd42c19a8a0210024bc00793c475814f00b095807c
INFO:     2025-09-18 10:16:39 [uvicorn.access] 127.0.0.1:37040 - "GET /api/stacks/transmission/transmission?no_cache=true HTTP/1.1" 200
```

Apparently, it should be updated, but in fact it is not. I can run more tests, as needed. Thank you for yor excellent container!
